const englishQuestions = [
      ["Who wrote 'Romeo and Juliet'?", "William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain", "William Shakespeare wrote 'Romeo and Juliet'."],
      ["What is a synonym of 'happy'?", "Joyful", "Angry", "Sad", "Tired", "A synonym for 'happy' is 'joyful'."],
  ["What figure of speech is used in 'The wind whispered through the trees'?", "Personification", "Simile", "Metaphor", "Alliteration", "'The wind whispered' gives human traits to wind, which is personification."],
  ["Who wrote 'To Kill a Mockingbird'?", "Harper Lee", "Ernest Hemingway", "F. Scott Fitzgerald", "J.D. Salinger", "Harper Lee is the author of 'To Kill a Mockingbird'."],
  ["Which sentence is grammatically correct?", "She has already eaten lunch.", "She already has ate lunch.", "She already eaten lunch.", "She has eat lunch.", "'She has already eaten lunch' is in correct present perfect tense."],
  ["What is the past tense of 'go'?", "Went", "Goed", "Gone", "Goes", "'Went' is the correct past tense of 'go'."],
  ["Which of these is an example of a simile?", "Her smile was as bright as the sun.", "Time is a thief.", "The leaves danced.", "He has a heart of stone.", "A simile uses 'as' or 'like' to compare, as in 'as bright as the sun'."],
  ["Who wrote '1984'?", "George Orwell", "Aldous Huxley", "Ray Bradbury", "Philip K. Dick", "George Orwell wrote '1984', a dystopian novel."],
  ["What is an antonym for 'generous'?", "Stingy", "Kind", "Helpful", "Giving", "'Stingy' means the opposite of 'generous'."],
  ["Which part of speech is the word 'quickly'?", "Adverb", "Adjective", "Noun", "Verb", "'Quickly' describes how something is done, so it's an adverb."],
  ["Who wrote 'The Great Gatsby'?", "F. Scott Fitzgerald", "John Steinbeck", "William Faulkner", "T.S. Eliot", "F. Scott Fitzgerald is the author of 'The Great Gatsby'."],
  ["'He’s a night owl.' is an example of:", "Metaphor", "Simile", "Personification", "Hyperbole", "'Night owl' compares a person to an owl without using 'like' or 'as', which is a metaphor."],
  ["What is the plural of 'child'?", "Children", "Childs", "Childes", "Childer", "The irregular plural of 'child' is 'children'."],
  ["Who wrote 'Pride and Prejudice'?", "Jane Austen", "Emily Brontë", "Louisa May Alcott", "Mary Shelley", "Jane Austen wrote 'Pride and Prejudice'."],
  ["Which sentence uses correct subject-verb agreement?", "The team is winning.", "The team are winning.", "The team were winning.", "The team be winning.", "'The team is winning' correctly treats 'team' as a singular subject."],
  ["Which is a hyperbole?", "I'm so hungry I could eat a horse.", "He is as brave as a lion.", "The sun smiled down.", "The car zoomed by.", "An exaggeration like 'eat a horse' is a hyperbole."],
  ["Who is the author of 'Moby-Dick'?", "Herman Melville", "Nathaniel Hawthorne", "Edgar Allan Poe", "Mark Twain", "Herman Melville wrote the classic novel 'Moby-Dick'."],
  ["Which word is a conjunction?", "Because", "Quickly", "House", "Sing", "'Because' is a subordinating conjunction."],
  ["Which is an example of alliteration?", "Sally sells seashells by the seashore.", "The wind howled.", "He is as tall as a giraffe.", "Her voice was music.", "Alliteration repeats initial consonant sounds, like 's' in this example."],
  ["Who wrote 'The Catcher in the Rye'?", "J.D. Salinger", "John Green", "Jack London", "Toni Morrison", "J.D. Salinger wrote 'The Catcher in the Rye'."],
  ["Which sentence is in passive voice?", "The book was read by Mary.", "Mary read the book.", "Mary is reading the book.", "Mary reads books.", "'Was read by Mary' is in passive voice."],
  ["What is the comparative form of 'good'?", "Better", "Gooder", "More good", "Best", "'Better' is the correct comparative form of 'good'."],
  ["Who is the author of 'Frankenstein'?", "Mary Shelley", "Bram Stoker", "Oscar Wilde", "H.G. Wells", "Mary Shelley wrote 'Frankenstein'."],
  ["What type of figurative language is 'The classroom was a zoo'?", "Metaphor", "Simile", "Hyperbole", "Personification", "It compares a classroom to a zoo directly, making it a metaphor."],
  ["Choose the correct plural form: 'analysis'", "Analyses", "Analysises", "Analys", "Analysis", "The plural of 'analysis' is 'analyses'."],
  ["Who wrote 'The Old Man and the Sea'?", "Ernest Hemingway", "William Faulkner", "F. Scott Fitzgerald", "John Steinbeck", "Ernest Hemingway wrote 'The Old Man and the Sea'."],
  ["Which is a simile?", "He ran like the wind.", "He is the wind.", "The wind whispered.", "The wind was his companion.", "A simile uses 'like' or 'as', like 'ran like the wind'."],
  ["What is the superlative form of 'bad'?", "Worst", "Badder", "More bad", "Baddest", "'Worst' is the superlative form of 'bad'."],
  ["Who wrote 'The Raven'?", "Edgar Allan Poe", "Walt Whitman", "Emily Dickinson", "Robert Frost", "Edgar Allan Poe wrote the poem 'The Raven'."],
  ["Which sentence is punctuated correctly?", "Yes, I will come.", "Yes I will come.", "Yes I, will come.", "Yes I will, come.", "'Yes, I will come.' correctly uses a comma after the introductory word."],
  ["Which word is an interjection?", "Wow", "Slow", "Run", "Blue", "'Wow' is an interjection used to express emotion."],
  ["Who wrote 'The Hobbit'?", "J.R.R. Tolkien", "C.S. Lewis", "George R.R. Martin", "J.K. Rowling", "J.R.R. Tolkien wrote 'The Hobbit'."],
  ["What is the synonym of 'brave'?", "Courageous", "Cowardly", "Shy", "Weak", "'Courageous' means the same as 'brave'."],
  ["What figure of speech is 'Boom! The door slammed shut'?", "Onomatopoeia", "Simile", "Metaphor", "Hyperbole", "'Boom' imitates a sound, making it onomatopoeia."],
  ["Who is the author of 'The Odyssey'?", "Homer", "Virgil", "Sophocles", "Euripides", "Homer is credited with writing 'The Odyssey'."],
  ["What is the function of an adjective?", "To describe a noun", "To show action", "To link ideas", "To name a person", "Adjectives describe or modify nouns."],
  ["What kind of figurative language is 'Her heart sank'?", "Metaphor", "Simile", "Alliteration", "Hyperbole", "It metaphorically suggests she felt disappointment, making it a metaphor."],
  ["Who wrote 'A Tale of Two Cities'?", "Charles Dickens", "Leo Tolstoy", "Victor Hugo", "Fyodor Dostoevsky", "Charles Dickens wrote 'A Tale of Two Cities'."],
  ["What is the correct form: 'He _____ to school every day.'", "goes", "go", "going", "gone", "'Goes' is the correct present simple form for 'he'."],
  ["Which is an example of personification?", "The stars danced in the sky.", "As fast as a cheetah.", "She’s a gem.", "So hungry I could eat a horse.", "Giving stars the human action of 'dancing' is personification."],
  ["Who wrote 'Leaves of Grass'?", "Walt Whitman", "Robert Frost", "Langston Hughes", "Carl Sandburg", "Walt Whitman is the author of 'Leaves of Grass'."]
["Who wrote 'Pride and Prejudice'?", "Jane Austen", "Charles Dickens", "Mark Twain", "William Shakespeare", "Jane Austen wrote 'Pride and Prejudice'."],
    ["What is a metaphor?", "A comparison without 'like' or 'as'", "A direct statement", "An exaggeration", "A sound device", "A metaphor compares two things without using 'like' or 'as'."],
    ["Which literary genre focuses on imaginary worlds and magic?", "Fantasy", "Nonfiction", "Historical Fiction", "Biography", "Fantasy literature includes magical elements and imaginary worlds."],
    ["What is the plural form of 'child'?", "Children", "Childs", "Childes", "Childing", "'Children' is the correct plural form of 'child'."],
    ["Who is the protagonist in 'Hamlet'?", "Hamlet", "Ophelia", "Macbeth", "Romeo", "The protagonist of 'Hamlet' is Prince Hamlet."],
    ["Which figure of speech gives human qualities to non-human objects?", "Personification", "Simile", "Metaphor", "Onomatopoeia", "Personification assigns human qualities to non-human things."],
    ["What is the subject of the sentence: 'The cat sat on the mat'?", "The cat", "The mat", "Sat", "On", "'The cat' is the subject of the sentence."],
    ["Which author wrote 'The Great Gatsby'?", "F. Scott Fitzgerald", "Ernest Hemingway", "Harper Lee", "J.K. Rowling", "F. Scott Fitzgerald wrote 'The Great Gatsby'."],
    ["What type of poem has 14 lines and a specific rhyme scheme?", "Sonnet", "Haiku", "Limerick", "Ballad", "A sonnet has 14 lines with a specific rhyme scheme."],
    ["What is an antonym for 'brave'?", "Cowardly", "Fearless", "Strong", "Daring", "An antonym for 'brave' is 'cowardly'."],
    ["Who wrote 'To Kill a Mockingbird'?", "Harper Lee", "J.D. Salinger", "George Orwell", "William Faulkner", "Harper Lee wrote 'To Kill a Mockingbird'."],
    ["What does 'hyperbole' mean?", "Extreme exaggeration", "Direct comparison", "Hinting at something", "Opposite meaning", "Hyperbole is an extreme exaggeration used for effect."],
    ["Which literary movement emphasized emotion and nature?", "Romanticism", "Realism", "Modernism", "Naturalism", "Romanticism emphasized emotion, nature, and individualism."],
    ["Who wrote '1984'?", "George Orwell", "Aldous Huxley", "Ray Bradbury", "Jules Verne", "George Orwell wrote '1984'."],
    ["Which type of noun refers to a person, place, or thing?", "Proper noun", "Abstract noun", "Collective noun", "Pronoun", "A proper noun refers to specific people, places, or things."],
    ["What is alliteration?", "Repetition of initial sounds", "Using a metaphor", "Making a comparison", "Telling a story", "Alliteration is the repetition of the same initial consonant sounds."],
    ["Which novel features the character Jay Gatsby?", "The Great Gatsby", "Moby *****", "Crime and Punishment", "Wuthering Heights", "Jay Gatsby is the main character in 'The Great Gatsby'."],
    ["What is the opposite of 'expand'?", "Shrink", "Grow", "Increase", "Enlarge", "The opposite of 'expand' is 'shrink'."],
    ["Which author wrote 'The Catcher in the Rye'?", "J.D. Salinger", "John Steinbeck", "Leo Tolstoy", "Virginia Woolf", "J.D. Salinger wrote 'The Catcher in the Rye'."],
    ["What does irony mean?", "Unexpected contrast between reality and expectations", "A direct statement", "A sound device", "A symbolic meaning", "Irony occurs when reality is different from expectations."],
    ["Who is the narrator in 'Moby-Dick'?", "Ishmael", "Ahab", "Starbuck", "Queequeg", "Ishmael is the narrator in 'Moby *****'."],
    ["What is the past tense of 'run'?", "Ran", "Runned", "Runs", "Running", "'Ran' is the correct past tense of 'run'."],
    ["Who wrote 'Frankenstein'?", "Mary Shelley", "Bram Stoker", "Edgar Allan Poe", "Charlotte Brontë", "Mary Shelley wrote 'Frankenstein'."],
    ["What is a simile?", "A comparison using 'like' or 'as'", "A direct statement", "An exaggeration", "A repeated sound", "A simile compares two things using 'like' or 'as'."],
    ["What literary device hints at future events?", "Foreshadowing", "Flashback", "Alliteration", "Hyperbole", "Foreshadowing provides hints about upcoming events in a story."],
    ["Who wrote 'Romeo and Juliet'?", "William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain", "William Shakespeare wrote 'Romeo and Juliet'."],
    ["What does a biography focus on?", "A person's life", "Fictional events", "Mythology", "Imaginary creatures", "A biography tells the life story of a real person."],
    ["What is the synonym for 'begin'?", "Start", "End", "Stop", "Pause", "A synonym for 'begin' is 'start'."],
    ["What is the setting of a story?", "Time and place", "Main character", "Conflict", "Theme", "The setting includes time and place where a story occurs."],
    ["Who wrote 'The Odyssey'?", "Homer", "Virgil", "Sophocles", "Plato", "Homer wrote 'The Odyssey'."],
    ["What is an allegory?", "A story with hidden meaning", "A direct statement", "A humorous exaggeration", "A type of rhyme", "An allegory is a story with a symbolic or hidden meaning."],
    ["Who wrote 'Macbeth'?", "William Shakespeare", "Christopher Marlowe", "John Milton", "Geoffrey Chaucer", "William Shakespeare wrote 'Macbeth'."],
    ["What is the main theme of 'Animal Farm'?", "Corruption of power", "Romantic love", "Exploration of space", "Coming of age", "'Animal Farm' explores the theme of power and corruption."],
    ["What is the difference between mood and tone?", "Mood is the reader's feeling, tone is the author's attitude", "Mood is the author’s attitude, tone is the reader's feeling", "They are the same", "Tone is only found in poetry", "Mood affects the reader, while tone reflects the author's attitude."],
    ["Who wrote 'Don Quixote'?", "Miguel de Cervantes", "Fyodor Dostoevsky", "Leo Tolstoy", "Herman Melville", "Miguel de Cervantes wrote 'Don Quixote'."],
    ["What is the correct comparative form of 'bad'?", "Worse", "Bader", "More bad", "Badder", "The comparative form of 'bad' is 'worse'."],
    ["What is the climax of a story?", "The most intense moment", "The introduction", "The conclusion", "The setting", "The climax is the most intense moment in a story."],
    ["Who wrote 'Les Misérables'?", "Victor Hugo", "Alexandre Dumas", "Gustave Flaubert", "Charles Dickens", "Victor Hugo wrote 'Les Misérables'."],
  ];
