const filipinoQuestions = [
    ["Sino ang sumulat ng 'Noli Me Tangere'?", "Jose Rizal", "Andres Bonifacio", "Emilio Aguinaldo", "Francisco Balagtas", "Si Jose Rizal ang sumulat ng 'Noli Me Tangere'."],
    ["Ano ang kahulugan ng 'talinhaga'?", "Malalim na pahiwatig", "Tuwirang kahulugan", "Patula lamang", "Pang-uri ng salita", "Ang talinhaga ay isang malalim na pahiwatig o matalinghagang pananalita."],
    ["Ano ang tawag sa panitikang nagsasalaysay ng kasaysayan ng isang tao?", "Talambuhay", "Epiko", "Awit", "Bugtong", "Ang talambuhay ay kwento ng buhay ng isang tao."],
    ["Ano ang pangunahing tema ng 'Florante at Laura'?", "Pag-ibig at pagtataksil", "Digmaan", "Kalikasan", "Paglalakbay", "Ang pangunahing tema ng 'Florante at Laura' ay pag-ibig at pagtataksil."],
    ["Ano ang ibig sabihin ng tayutay?", "Matalinghagang pagpapahayag", "Tuwirang paliwanag", "Pag-uulit ng salita", "Paggamit ng pang-uri", "Ang tayutay ay matalinghagang pagpapahayag ng damdamin."],
    ["Ano ang kahulugan ng 'pabula'?", "Kwento tungkol sa hayop na may aral", "Kwento ng katatakutan", "Patulang panitikan", "Tula tungkol sa kalikasan", "Ang pabula ay isang kwentong may hayop bilang tauhan na may aral."],
    ["Ano ang salitang magkasalungat ng 'malungkot'?", "Masaya", "Mahina", "Matamlay", "Madilim", "Ang salitang magkasalungat ng 'malungkot' ay 'masaya'."],
    ["Sino ang may-akda ng 'Ibong Adarna'?", "Hindi tiyak", "Francisco Balagtas", "Jose Rizal", "Emilio Jacinto", "Ang may-akda ng 'Ibong Adarna' ay hindi tiyak dahil ito ay isang sinaunang akdang pampanitikan."],
    ["Ano ang palasak na anyo ng tula na may 4 na taludtod bawat saknong?", "Quatrain", "Couplet", "Soneto", "Balagtasan", "Ang quatrain ay isang uri ng tula na may apat na taludtod sa bawat saknong."],
    ["Ano ang tambalang salita ng 'bahaghari'?", "Bahag + Hari", "Bahagi + Hari", "Baha + Hari", "Bahay + Hari", "Ang tambalang salita ng 'bahaghari' ay 'bahag' at 'hari'."],
    ["Ano ang kahulugan ng idyoma na 'kapit sa patalim'?", "Pagsasakripisyo para sa pangangailangan", "Pag-aalaga ng matalim na bagay", "Pag-iiwas sa panganib", "Pagkawala ng pag-asa", "Ang 'kapit sa patalim' ay nangangahulugang pagsasakripisyo para sa pangangailangan."],
    ["Ano ang gamit ng pandiwa sa pangungusap: 'Siya ay tumakbo nang mabilis'?", "Kilos o galaw", "Ngalan ng tao", "Paglalarawan", "Pananda ng pang-abay", "Ang pandiwa ay tumutukoy sa kilos o galaw."],
    ["Ano ang kahulugan ng 'parabula'?", "Kwento na may aral mula sa bibliya", "Kwento ng hayop", "Kwento ng digmaan", "Kwento ng misteryo", "Ang parabula ay isang kwento na may aral mula sa bibliya."],
    ["Ano ang tawag sa paligsahan ng matatalas na debate sa pagtula?", "Balagtasan", "Bugtungan", "Talumpati", "Sanaysay", "Ang Balagtasan ay isang paligsahan ng pagtula na may matatalas na argumento."],
    ["Ano ang salitang ugat ng 'pinag-aralan'?", "Aral", "Pag-aaral", "Pinag-aral", "Nag-aral", "Ang salitang ugat ng 'pinag-aralan' ay 'aral'."],
    ["Ano ang kahulugan ng 'masining na pagpapahayag'?", "Malikhain at pino ang gamit ng salita", "Tuwirang paliwanag", "Pag-uulit ng impormasyon", "Makabago at teknikal na pagsasalita", "Ang masining na pagpapahayag ay malikhain at pino ang gamit ng salita."],
    ["Ano ang elemento ng tula na tumutukoy sa tunog at ritmo?", "Sukat at tugma", "Tema", "Tauhan", "Banghay", "Ang sukat at tugma ay elemento ng tula na tumutukoy sa tunog at ritmo."],
    ["Ano ang ibig sabihin ng 'Alamat'?", "Kwento ng pinagmulan ng isang bagay", "Kwento ng kasaysayan", "Kwento ng pantasya", "Kwento ng katatakutan", "Ang alamat ay kwento ng pinagmulan ng isang bagay o lugar."],
  ];
