const questionBank = {
    Math: [
     ["What is 15 \u00D7 3?", "45", "40", "50", "35", "15 times 3 equals 45."],
    ["What is 144 ÷ 12?", "12", "10", "14", "16", "144 divided by 12 is 12."],
    ["What is the square of 9?", "81", "72", "90", "99", "The square of 9 is 81 because 9 \u00D7 9 = 81."],
    ["What is the cube root of 27?", "3", "9", "6", "4", "The cube root of 27 is 3 because 3 \u00D7 3 \u00D7 3 = 27."],
    ["If a triangle has angles of 40° and 50°, what is the third angle?", "90°", "60°", "80°", "70°", "The third angle is 90° because the sum of a triangle's angles is always 180°."],
    ["What is the least common multiple (LCM) of 4 and 6?", "12", "24", "6", "18", "The least common multiple of 4 and 6 is 12."],
    ["What is 25% of 200?", "50", "25", "100", "75", "25% of 200 is 50."],
    ["What is the greatest common divisor (GCD) of 28 and 42?", "14", "7", "21", "28", "The greatest common divisor of 28 and 42 is 14."],
    ["What is the sum of the interior angles of a pentagon?", "540°", "360°", "720°", "180°", "The sum of the interior angles of a pentagon is 540°."],
    ["What is the next prime number after 19?", "23", "21", "25", "27", "The next prime number after 19 is 23."],
    ["If 8x = 64, what is x?", "8", "6", "4", "10", "If 8x = 64, then x = 8."],
    ["What is the area of a rectangle with width 10 and length 15?", "150", "125", "160", "140", "The area of a rectangle is found using length \u00D7 width, so 10 \u00D7 15 = 150."],
    ["What is the perimeter of a square with a side length of 7?", "28", "21", "35", "49", "The perimeter of a square is 4 times the side length, so 7 \u00D7 4 = 28."],
    ["What is the median of 3, 7, 9, 13, 15?", "9", "7", "13", "15", "The median is the middle value, which is 9."],
    ["What is the probability of rolling a 6 on a fair six-sided die?", "1/6", "1/3", "1/2", "1/4", "The probability of rolling a 6 is 1 out of 6 possible outcomes, or 1/6."],
    ["What is the value of π rounded to two decimal places?", "3.14", "3.16", "3.12", "3.18", "π is approximately 3.14."],
    ["What is the equation of a line with slope 5 passing through (2, 10)?", "y = 5x", "y = 5x + 0", "y = 5x + 1", "y = 5x - 2", "Using the slope-intercept formula, the equation is y = 5x."],
    ["If a car travels 60 km/h for 3 hours, how far does it go?", "180 km", "120 km", "200 km", "150 km", "Distance = speed \u00D7 time, so 60 \u00D7 3 = 180 km."],
    ["What is the volume of a cube with side length 4?", "64", "32", "16", "48", "The volume of a cube is side³, so 4 \u00D7 4 \u00D7 4 = 64."],
    ["What is the radius of a circle with a diameter of 12?", "6", "12", "3", "9", "The radius is half of the diameter, so 12 ÷ 2 = 6."],
    ["Solve for x: 3x - 5 = 10.", "5", "3", "7", "8", "Adding 5 to both sides and dividing by 3 gives x = 5."],
    ["What is the factorial of 5?", "120", "60", "20", "24", "5! = 5 \u00D7 4 \u00D7 3 \u00D7 2 \u00D7 1 = 120."],
    ["Convert 0.75 to a fraction.", "3/4", "2/3", "1/2", "5/8", "0.75 as a fraction is 3/4."],
    ["What is the slope of the line passing through (2,4) and (5,10)?", "2", "3", "4", "5", "Slope = (10 - 4) / (5 - 2) = 2."],
    ["What is the sum of the first 5 natural numbers?", "15", "10", "20", "12", "The sum is 1+2+3+4+5 = 15."],
    ["What is the hypotenuse of a right triangle with legs 6 and 8?", "10", "12", "14", "8", "Using the Pythagorean theorem, hypotenuse = √(6² + 8²) = 10."],
    ["What is the reciprocal of 5?", "1/5", "5", "10", "1/10", "The reciprocal of 5 is 1/5."],
    ["What is the logarithm of 100 to base 10?", "2", "10", "5", "1", "log₁₀(100) = 2 because 10² = 100."],
    ["What is 8% of 250?", "20", "10", "15", "25", "8% of 250 is 20."],
    ["Solve for x: x² = 49.", "7", "6", "8", "5", "Taking the square root of both sides gives x = 7."],
    ["What is the mode of {4, 4, 5, 6, 4, 7, 5}?", "4", "5", "6", "7", "Mode is the most frequent number, which is 4."],
    ["What is the circumference of a circle with radius 10?", "62.8", "31.4", "50.2", "70.8", "Circumference = 2πr, so 2 \u00D7 3.14 \u00D7 10 ≈ 62.8."],
    ["What is the derivative of x²?", "2x", "x", "x²", "3x", "The derivative of x² is 2x."],
    ["How many degrees are in a straight line?", "180°", "90°", "360°", "120°", "A straight line has 180°."],
    ["What is the product of 0.5 and 0.4?", "0.2", "0.5", "0.4", "0.25", "0.5 \u00D7 0.4 = 0.2."],
    ["What is the sum of angles in a quadrilateral?", "360°", "180°", "270°", "450°", "A quadrilateral's angles sum to 360°."]
  ],
    Science: [
      ["What is the boiling point of water?", "100°C", "50°C", "200°C", "150°C", "Water boils at 100°C under normal atmospheric pressure."],
    ["Which gas is most abundant in Earth's atmosphere?", "Nitrogen", "Oxygen", "Carbon Dioxide", "Hydrogen", "Nitrogen makes up about 78% of Earth's atmosphere."],
    ["What force keeps planets in orbit around the Sun?", "Gravity", "Magnetism", "Friction", "Tension", "Gravity is the force that keeps planets in orbit around the Sun."],
    ["What is the basic unit of life?", "Cell", "Atom", "Molecule", "Organ", "The cell is the basic unit of life in all living organisms."],
    ["Which vitamin is mainly obtained from sunlight?", "Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B", "Vitamin D is produced in the skin when exposed to sunlight."],
    ["What is the hardest natural substance on Earth?", "Diamond", "Gold", "Iron", "Quartz", "Diamond is the hardest natural substance known."],
    ["Which organ in the human body pumps blood?", "Heart", "Liver", "Lungs", "Kidney", "The heart pumps blood throughout the body."],
    ["What is the primary function of the lungs?", "Breathing", "Digestion", "Circulation", "Excretion", "The lungs facilitate breathing by exchanging oxygen and carbon dioxide."],
    ["What is Earth's largest ocean?", "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "The Pacific Ocean is the largest ocean on Earth."],
    ["What do bees collect to make honey?", "Nectar", "Pollen", "Water", "Leaves", "Bees collect nectar from flowers to produce honey."],
    ["What planet is closest to the Sun?", "Mercury", "Venus", "Earth", "Mars", "Mercury is the closest planet to the Sun."],
    ["What is the chemical symbol for gold?", "Au", "Ag", "Fe", "Hg", "The chemical symbol for gold is Au."],
    ["What kind of energy is stored in food?", "Chemical Energy", "Thermal Energy", "Electrical Energy", "Mechanical Energy", "Food stores chemical energy used by living organisms."],
    ["Which gas do humans exhale when they breathe?", "Carbon Dioxide", "Oxygen", "Nitrogen", "Helium", "Humans exhale carbon dioxide after respiration."],
    ["What type of blood cells help fight infections?", "White Blood Cells", "Red Blood Cells", "Platelets", "Plasma", "White blood cells help defend the body against infections."],
    ["What is the process by which plants make their food?", "Photosynthesis", "Respiration", "Fermentation", "Digestion", "Photosynthesis is the process plants use to produce food using sunlight."],
    ["Which part of the plant absorbs water?", "Roots", "Leaves", "Stem", "Flowers", "Roots absorb water and nutrients from the soil."],
    ["What does a thermometer measure?", "Temperature", "Pressure", "Speed", "Density", "A thermometer measures temperature."],
    ["What causes tides in the ocean?", "Moon's gravity", "Sun's heat", "Wind", "Earth's rotation", "The Moon's gravitational pull is the main cause of ocean tides."],
    ["What instrument is used to measure earthquakes?", "Seismometer", "Barometer", "Thermometer", "Compass", "A seismometer detects and measures earthquakes."]
  ],
    English: [
      ["Who wrote 'Romeo and Juliet'?", "William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain", "William Shakespeare wrote 'Romeo and Juliet'."],
      ["What is a synonym of 'happy'?", "Joyful", "Angry", "Sad", "Tired", "A synonym for 'happy' is 'joyful'."],
    
  ["What figure of speech is used in 'The wind whispered through the trees'?", "Personification", "Simile", "Metaphor", "Alliteration", "'The wind whispered' gives human traits to wind, which is personification."],
  ["Who wrote 'To Kill a Mockingbird'?", "Harper Lee", "Ernest Hemingway", "F. Scott Fitzgerald", "J.D. Salinger", "Harper Lee is the author of 'To Kill a Mockingbird'."],
  ["Which sentence is grammatically correct?", "She has already eaten lunch.", "She already has ate lunch.", "She already eaten lunch.", "She has eat lunch.", "'She has already eaten lunch' is in correct present perfect tense."],
  ["What is the past tense of 'go'?", "Went", "Goed", "Gone", "Goes", "'Went' is the correct past tense of 'go'."],
  ["Which of these is an example of a simile?", "Her smile was as bright as the sun.", "Time is a thief.", "The leaves danced.", "He has a heart of stone.", "A simile uses 'as' or 'like' to compare, as in 'as bright as the sun'."],
  ["Who wrote '1984'?", "George Orwell", "Aldous Huxley", "Ray Bradbury", "Philip K. Dick", "George Orwell wrote '1984', a dystopian novel."],
  ["What is an antonym for 'generous'?", "Stingy", "Kind", "Helpful", "Giving", "'Stingy' means the opposite of 'generous'."],
  ["Which part of speech is the word 'quickly'?", "Adverb", "Adjective", "Noun", "Verb", "'Quickly' describes how something is done, so it's an adverb."],
  ["Who wrote 'The Great Gatsby'?", "F. Scott Fitzgerald", "John Steinbeck", "William Faulkner", "T.S. Eliot", "F. Scott Fitzgerald is the author of 'The Great Gatsby'."],
  ["'He’s a night owl.' is an example of:", "Metaphor", "Simile", "Personification", "Hyperbole", "'Night owl' compares a person to an owl without using 'like' or 'as', which is a metaphor."],
  ["What is the plural of 'child'?", "Children", "Childs", "Childes", "Childer", "The irregular plural of 'child' is 'children'."],
  ["Who wrote 'Pride and Prejudice'?", "Jane Austen", "Emily Brontë", "Louisa May Alcott", "Mary Shelley", "Jane Austen wrote 'Pride and Prejudice'."],
  ["Which sentence uses correct subject-verb agreement?", "The team is winning.", "The team are winning.", "The team were winning.", "The team be winning.", "'The team is winning' correctly treats 'team' as a singular subject."],
  ["Which is a hyperbole?", "I'm so hungry I could eat a horse.", "He is as brave as a lion.", "The sun smiled down.", "The car zoomed by.", "An exaggeration like 'eat a horse' is a hyperbole."],
  ["Who is the author of 'Moby-Dick'?", "Herman Melville", "Nathaniel Hawthorne", "Edgar Allan Poe", "Mark Twain", "Herman Melville wrote the classic novel 'Moby-Dick'."],
  ["Which word is a conjunction?", "Because", "Quickly", "House", "Sing", "'Because' is a subordinating conjunction."],
  ["Which is an example of alliteration?", "Sally sells seashells by the seashore.", "The wind howled.", "He is as tall as a giraffe.", "Her voice was music.", "Alliteration repeats initial consonant sounds, like 's' in this example."],
  ["Who wrote 'The Catcher in the Rye'?", "J.D. Salinger", "John Green", "Jack London", "Toni Morrison", "J.D. Salinger wrote 'The Catcher in the Rye'."],
  ["Which sentence is in passive voice?", "The book was read by Mary.", "Mary read the book.", "Mary is reading the book.", "Mary reads books.", "'Was read by Mary' is in passive voice."],
  ["What is the comparative form of 'good'?", "Better", "Gooder", "More good", "Best", "'Better' is the correct comparative form of 'good'."],
  ["Who is the author of 'Frankenstein'?", "Mary Shelley", "Bram Stoker", "Oscar Wilde", "H.G. Wells", "Mary Shelley wrote 'Frankenstein'."],
  ["What type of figurative language is 'The classroom was a zoo'?", "Metaphor", "Simile", "Hyperbole", "Personification", "It compares a classroom to a zoo directly, making it a metaphor."],
  ["Choose the correct plural form: 'analysis'", "Analyses", "Analysises", "Analys", "Analysis", "The plural of 'analysis' is 'analyses'."],
  ["Who wrote 'The Old Man and the Sea'?", "Ernest Hemingway", "William Faulkner", "F. Scott Fitzgerald", "John Steinbeck", "Ernest Hemingway wrote 'The Old Man and the Sea'."],
  ["Which is a simile?", "He ran like the wind.", "He is the wind.", "The wind whispered.", "The wind was his companion.", "A simile uses 'like' or 'as', like 'ran like the wind'."],
  ["What is the superlative form of 'bad'?", "Worst", "Badder", "More bad", "Baddest", "'Worst' is the superlative form of 'bad'."],
  ["Who wrote 'The Raven'?", "Edgar Allan Poe", "Walt Whitman", "Emily Dickinson", "Robert Frost", "Edgar Allan Poe wrote the poem 'The Raven'."],
  ["Which sentence is punctuated correctly?", "Yes, I will come.", "Yes I will come.", "Yes I, will come.", "Yes I will, come.", "'Yes, I will come.' correctly uses a comma after the introductory word."],
  ["Which word is an interjection?", "Wow", "Slow", "Run", "Blue", "'Wow' is an interjection used to express emotion."],
  ["Who wrote 'The Hobbit'?", "J.R.R. Tolkien", "C.S. Lewis", "George R.R. Martin", "J.K. Rowling", "J.R.R. Tolkien wrote 'The Hobbit'."],
  ["What is the synonym of 'brave'?", "Courageous", "Cowardly", "Shy", "Weak", "'Courageous' means the same as 'brave'."],
  ["What figure of speech is 'Boom! The door slammed shut'?", "Onomatopoeia", "Simile", "Metaphor", "Hyperbole", "'Boom' imitates a sound, making it onomatopoeia."],
  ["Who is the author of 'The Odyssey'?", "Homer", "Virgil", "Sophocles", "Euripides", "Homer is credited with writing 'The Odyssey'."],
  ["What is the function of an adjective?", "To describe a noun", "To show action", "To link ideas", "To name a person", "Adjectives describe or modify nouns."],
  ["What kind of figurative language is 'Her heart sank'?", "Metaphor", "Simile", "Alliteration", "Hyperbole", "It metaphorically suggests she felt disappointment, making it a metaphor."],
  ["Who wrote 'A Tale of Two Cities'?", "Charles Dickens", "Leo Tolstoy", "Victor Hugo", "Fyodor Dostoevsky", "Charles Dickens wrote 'A Tale of Two Cities'."],
  ["What is the correct form: 'He _____ to school every day.'", "goes", "go", "going", "gone", "'Goes' is the correct present simple form for 'he'."],
  ["Which is an example of personification?", "The stars danced in the sky.", "As fast as a cheetah.", "She’s a gem.", "So hungry I could eat a horse.", "Giving stars the human action of 'dancing' is personification."],
  ["Who wrote 'Leaves of Grass'?", "Walt Whitman", "Robert Frost", "Langston Hughes", "Carl Sandburg", "Walt Whitman is the author of 'Leaves of Grass'."]
]
  };

