const questionBank = {
    Math: [
    ["What is 15 \u00D7 3?", "45", "40", "50", "35", "15 times 3 equals 45."],
    ["What is 144 ÷ 12?", "12", "10", "14", "16", "144 divided by 12 is 12."],
    ["What is the square of 9?", "81", "72", "90", "99", "The square of 9 is 81 because 9 \u00D7 9 = 81."],
    ["What is the cube root of 27?", "3", "9", "6", "4", "The cube root of 27 is 3 because 3 \u00D7 3 \u00D7 3 = 27."],
    ["If a triangle has angles of 40° and 50°, what is the third angle?", "90°", "60°", "80°", "70°", "The third angle is 90° because the sum of a triangle's angles is always 180°."],
    ["What is the least common multiple (LCM) of 4 and 6?", "12", "24", "6", "18", "The least common multiple of 4 and 6 is 12."],
    ["What is 25% of 200?", "50", "25", "100", "75", "25% of 200 is 50."],
    ["What is the greatest common divisor (GCD) of 28 and 42?", "14", "7", "21", "28", "The greatest common divisor of 28 and 42 is 14."],
    ["What is the sum of the interior angles of a pentagon?", "540°", "360°", "720°", "180°", "The sum of the interior angles of a pentagon is 540°."],
    ["What is the next prime number after 19?", "23", "21", "25", "27", "The next prime number after 19 is 23."],
    ["If 8x = 64, what is x?", "8", "6", "4", "10", "If 8x = 64, then x = 8."],
    ["What is the area of a rectangle with width 10 and length 15?", "150", "125", "160", "140", "The area of a rectangle is found using length \u00D7 width, so 10 \u00D7 15 = 150."],
    ["What is the perimeter of a square with a side length of 7?", "28", "21", "35", "49", "The perimeter of a square is 4 times the side length, so 7 \u00D7 4 = 28."],
    ["What is the median of 3, 7, 9, 13, 15?", "9", "7", "13", "15", "The median is the middle value, which is 9."],
    ["What is the probability of rolling a 6 on a fair six-sided die?", "1/6", "1/3", "1/2", "1/4", "The probability of rolling a 6 is 1 out of 6 possible outcomes, or 1/6."],
    ["What is the value of π rounded to two decimal places?", "3.14", "3.16", "3.12", "3.18", "π is approximately 3.14."],
    ["What is the equation of a line with slope 5 passing through (2, 10)?", "y = 5x", "y = 5x + 0", "y = 5x + 1", "y = 5x - 2", "Using the slope-intercept formula, the equation is y = 5x."],
    ["If a car travels 60 km/h for 3 hours, how far does it go?", "180 km", "120 km", "200 km", "150 km", "Distance = speed \u00D7 time, so 60 \u00D7 3 = 180 km."],
    ["What is the volume of a cube with side length 4?", "64", "32", "16", "48", "The volume of a cube is side³, so 4 \u00D7 4 \u00D7 4 = 64."],
    ["What is the radius of a circle with a diameter of 12?", "6", "12", "3", "9", "The radius is half of the diameter, so 12 ÷ 2 = 6."],
    ["Solve for x: 3x - 5 = 10.", "5", "3", "7", "8", "Adding 5 to both sides and dividing by 3 gives x = 5."],
    ["What is the factorial of 5?", "120", "60", "20", "24", "5! = 5 \u00D7 4 \u00D7 3 \u00D7 2 \u00D7 1 = 120."],
    ["Convert 0.75 to a fraction.", "3/4", "2/3", "1/2", "5/8", "0.75 as a fraction is 3/4."],
    ["What is the slope of the line passing through (2,4) and (5,10)?", "2", "3", "4", "5", "Slope = (10 - 4) / (5 - 2) = 2."],
    ["What is the sum of the first 5 natural numbers?", "15", "10", "20", "12", "The sum is 1+2+3+4+5 = 15."],
    ["What is the hypotenuse of a right triangle with legs 6 and 8?", "10", "12", "14", "8", "Using the Pythagorean theorem, hypotenuse = √(6² + 8²) = 10."],
    ["What is the reciprocal of 5?", "1/5", "5", "10", "1/10", "The reciprocal of 5 is 1/5."],
    ["What is the logarithm of 100 to base 10?", "2", "10", "5", "1", "log₁₀(100) = 2 because 10² = 100."],
    ["What is 8% of 250?", "20", "10", "15", "25", "8% of 250 is 20."],
    ["Solve for x: x² = 49.", "7", "6", "8", "5", "Taking the square root of both sides gives x = 7."],
    ["What is the mode of {4, 4, 5, 6, 4, 7, 5}?", "4", "5", "6", "7", "Mode is the most frequent number, which is 4."],
    ["What is the circumference of a circle with radius 10?", "62.8", "31.4", "50.2", "70.8", "Circumference = 2πr, so 2 \u00D7 3.14 \u00D7 10 ≈ 62.8."],
    ["What is the derivative of x²?", "2x", "x", "x²", "3x", "The derivative of x² is 2x."],
    ["How many degrees are in a straight line?", "180°", "90°", "360°", "120°", "A straight line has 180°."],
    ["What is the product of 0.5 and 0.4?", "0.2", "0.5", "0.4", "0.25", "0.5 \u00D7 0.4 = 0.2."],
    ["What is the sum of angles in a quadrilateral?", "360°", "180°", "270°", "450°", "A quadrilateral's angles sum to 360°."],
  ],
    Science: [
      ["What is the boiling point of water?", "100°C", "50°C", "200°C", "150°C", "Water boils at 100°C under normal atmospheric pressure."],
    ["Which gas is most abundant in Earth's atmosphere?", "Nitrogen", "Oxygen", "Carbon Dioxide", "Hydrogen", "Nitrogen makes up about 78% of Earth's atmosphere."],
    ["What force keeps planets in orbit around the Sun?", "Gravity", "Magnetism", "Friction", "Tension", "Gravity is the force that keeps planets in orbit around the Sun."],
    ["What is the basic unit of life?", "Cell", "Atom", "Molecule", "Organ", "The cell is the basic unit of life in all living organisms."],
    ["Which vitamin is mainly obtained from sunlight?", "Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B", "Vitamin D is produced in the skin when exposed to sunlight."],
    ["What is the hardest natural substance on Earth?", "Diamond", "Gold", "Iron", "Quartz", "Diamond is the hardest natural substance known."],
    ["Which organ in the human body pumps blood?", "Heart", "Liver", "Lungs", "Kidney", "The heart pumps blood throughout the body."],
    ["What is the primary function of the lungs?", "Breathing", "Digestion", "Circulation", "Excretion", "The lungs facilitate breathing by exchanging oxygen and carbon dioxide."],
    ["What is Earth's largest ocean?", "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "The Pacific Ocean is the largest ocean on Earth."],
    ["What do bees collect to make honey?", "Nectar", "Pollen", "Water", "Leaves", "Bees collect nectar from flowers to produce honey."],
    ["What planet is closest to the Sun?", "Mercury", "Venus", "Earth", "Mars", "Mercury is the closest planet to the Sun."],
    ["What is the chemical symbol for gold?", "Au", "Ag", "Fe", "Hg", "The chemical symbol for gold is Au."],
    ["What kind of energy is stored in food?", "Chemical Energy", "Thermal Energy", "Electrical Energy", "Mechanical Energy", "Food stores chemical energy used by living organisms."],
    ["Which gas do humans exhale when they breathe?", "Carbon Dioxide", "Oxygen", "Nitrogen", "Helium", "Humans exhale carbon dioxide after respiration."],
    ["What type of blood cells help fight infections?", "White Blood Cells", "Red Blood Cells", "Platelets", "Plasma", "White blood cells help defend the body against infections."],
    ["What is the process by which plants make their food?", "Photosynthesis", "Respiration", "Fermentation", "Digestion", "Photosynthesis is the process plants use to produce food using sunlight."],
    ["Which part of the plant absorbs water?", "Roots", "Leaves", "Stem", "Flowers", "Roots absorb water and nutrients from the soil."],
    ["What does a thermometer measure?", "Temperature", "Pressure", "Speed", "Density", "A thermometer measures temperature."],
    ["What causes tides in the ocean?", "Moon's gravity", "Sun's heat", "Wind", "Earth's rotation", "The Moon's gravitational pull is the main cause of ocean tides."],
    ["What instrument is used to measure earthquakes?", "Seismometer", "Barometer", "Thermometer", "Compass", "A seismometer detects and measures earthquakes."]
  ],
    English: [
      ["Who wrote 'Romeo and Juliet'?", "William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain", "William Shakespeare wrote 'Romeo and Juliet'."],
      ["What is a synonym of 'happy'?", "Joyful", "Angry", "Sad", "Tired", "A synonym for 'happy' is 'joyful'."],
    
  ["What figure of speech is used in 'The wind whispered through the trees'?", "Personification", "Simile", "Metaphor", "Alliteration", "'The wind whispered' gives human traits to wind, which is personification."],
  ["Who wrote 'To Kill a Mockingbird'?", "Harper Lee", "Ernest Hemingway", "F. Scott Fitzgerald", "J.D. Salinger", "Harper Lee is the author of 'To Kill a Mockingbird'."],
  ["Which sentence is grammatically correct?", "She has already eaten lunch.", "She already has ate lunch.", "She already eaten lunch.", "She has eat lunch.", "'She has already eaten lunch' is in correct present perfect tense."],
  ["What is the past tense of 'go'?", "Went", "Goed", "Gone", "Goes", "'Went' is the correct past tense of 'go'."],
  ["Which of these is an example of a simile?", "Her smile was as bright as the sun.", "Time is a thief.", "The leaves danced.", "He has a heart of stone.", "A simile uses 'as' or 'like' to compare, as in 'as bright as the sun'."],
  ["Who wrote '1984'?", "George Orwell", "Aldous Huxley", "Ray Bradbury", "Philip K. Dick", "George Orwell wrote '1984', a dystopian novel."],
  ["What is an antonym for 'generous'?", "Stingy", "Kind", "Helpful", "Giving", "'Stingy' means the opposite of 'generous'."],
  ["Which part of speech is the word 'quickly'?", "Adverb", "Adjective", "Noun", "Verb", "'Quickly' describes how something is done, so it's an adverb."],
  ["Who wrote 'The Great Gatsby'?", "F. Scott Fitzgerald", "John Steinbeck", "William Faulkner", "T.S. Eliot", "F. Scott Fitzgerald is the author of 'The Great Gatsby'."],
  ["'He’s a night owl.' is an example of:", "Metaphor", "Simile", "Personification", "Hyperbole", "'Night owl' compares a person to an owl without using 'like' or 'as', which is a metaphor."],
  ["What is the plural of 'child'?", "Children", "Childs", "Childes", "Childer", "The irregular plural of 'child' is 'children'."],
  ["Who wrote 'Pride and Prejudice'?", "Jane Austen", "Emily Brontë", "Louisa May Alcott", "Mary Shelley", "Jane Austen wrote 'Pride and Prejudice'."],
  ["Which sentence uses correct subject-verb agreement?", "The team is winning.", "The team are winning.", "The team were winning.", "The team be winning.", "'The team is winning' correctly treats 'team' as a singular subject."],
  ["Which is a hyperbole?", "I'm so hungry I could eat a horse.", "He is as brave as a lion.", "The sun smiled down.", "The car zoomed by.", "An exaggeration like 'eat a horse' is a hyperbole."],
  ["Who is the author of 'Moby-Dick'?", "Herman Melville", "Nathaniel Hawthorne", "Edgar Allan Poe", "Mark Twain", "Herman Melville wrote the classic novel 'Moby-Dick'."],
  ["Which word is a conjunction?", "Because", "Quickly", "House", "Sing", "'Because' is a subordinating conjunction."],
  ["Which is an example of alliteration?", "Sally sells seashells by the seashore.", "The wind howled.", "He is as tall as a giraffe.", "Her voice was music.", "Alliteration repeats initial consonant sounds, like 's' in this example."],
  ["Who wrote 'The Catcher in the Rye'?", "J.D. Salinger", "John Green", "Jack London", "Toni Morrison", "J.D. Salinger wrote 'The Catcher in the Rye'."],
  ["Which sentence is in passive voice?", "The book was read by Mary.", "Mary read the book.", "Mary is reading the book.", "Mary reads books.", "'Was read by Mary' is in passive voice."],
  ["What is the comparative form of 'good'?", "Better", "Gooder", "More good", "Best", "'Better' is the correct comparative form of 'good'."],
  ["Who is the author of 'Frankenstein'?", "Mary Shelley", "Bram Stoker", "Oscar Wilde", "H.G. Wells", "Mary Shelley wrote 'Frankenstein'."],
  ["What type of figurative language is 'The classroom was a zoo'?", "Metaphor", "Simile", "Hyperbole", "Personification", "It compares a classroom to a zoo directly, making it a metaphor."],
  ["Choose the correct plural form: 'analysis'", "Analyses", "Analysises", "Analys", "Analysis", "The plural of 'analysis' is 'analyses'."],
  ["Who wrote 'The Old Man and the Sea'?", "Ernest Hemingway", "William Faulkner", "F. Scott Fitzgerald", "John Steinbeck", "Ernest Hemingway wrote 'The Old Man and the Sea'."],
  ["Which is a simile?", "He ran like the wind.", "He is the wind.", "The wind whispered.", "The wind was his companion.", "A simile uses 'like' or 'as', like 'ran like the wind'."],
  ["What is the superlative form of 'bad'?", "Worst", "Badder", "More bad", "Baddest", "'Worst' is the superlative form of 'bad'."],
  ["Who wrote 'The Raven'?", "Edgar Allan Poe", "Walt Whitman", "Emily Dickinson", "Robert Frost", "Edgar Allan Poe wrote the poem 'The Raven'."],
  ["Which sentence is punctuated correctly?", "Yes, I will come.", "Yes I will come.", "Yes I, will come.", "Yes I will, come.", "'Yes, I will come.' correctly uses a comma after the introductory word."],
  ["Which word is an interjection?", "Wow", "Slow", "Run", "Blue", "'Wow' is an interjection used to express emotion."],
  ["Who wrote 'The Hobbit'?", "J.R.R. Tolkien", "C.S. Lewis", "George R.R. Martin", "J.K. Rowling", "J.R.R. Tolkien wrote 'The Hobbit'."],
  ["What is the synonym of 'brave'?", "Courageous", "Cowardly", "Shy", "Weak", "'Courageous' means the same as 'brave'."],
  ["What figure of speech is 'Boom! The door slammed shut'?", "Onomatopoeia", "Simile", "Metaphor", "Hyperbole", "'Boom' imitates a sound, making it onomatopoeia."],
  ["Who is the author of 'The Odyssey'?", "Homer", "Virgil", "Sophocles", "Euripides", "Homer is credited with writing 'The Odyssey'."],
  ["What is the function of an adjective?", "To describe a noun", "To show action", "To link ideas", "To name a person", "Adjectives describe or modify nouns."],
  ["What kind of figurative language is 'Her heart sank'?", "Metaphor", "Simile", "Alliteration", "Hyperbole", "It metaphorically suggests she felt disappointment, making it a metaphor."],
  ["Who wrote 'A Tale of Two Cities'?", "Charles Dickens", "Leo Tolstoy", "Victor Hugo", "Fyodor Dostoevsky", "Charles Dickens wrote 'A Tale of Two Cities'."],
  ["What is the correct form: 'He _____ to school every day.'", "goes", "go", "going", "gone", "'Goes' is the correct present simple form for 'he'."],
  ["Which is an example of personification?", "The stars danced in the sky.", "As fast as a cheetah.", "She’s a gem.", "So hungry I could eat a horse.", "Giving stars the human action of 'dancing' is personification."],
  ["Who wrote 'Leaves of Grass'?", "Walt Whitman", "Robert Frost", "Langston Hughes", "Carl Sandburg", "Walt Whitman is the author of 'Leaves of Grass'."]
["Who wrote 'Pride and Prejudice'?", "Jane Austen", "Charles Dickens", "Mark Twain", "William Shakespeare", "Jane Austen wrote 'Pride and Prejudice'."],
    ["What is a metaphor?", "A comparison without 'like' or 'as'", "A direct statement", "An exaggeration", "A sound device", "A metaphor compares two things without using 'like' or 'as'."],
    ["Which literary genre focuses on imaginary worlds and magic?", "Fantasy", "Nonfiction", "Historical Fiction", "Biography", "Fantasy literature includes magical elements and imaginary worlds."],
    ["What is the plural form of 'child'?", "Children", "Childs", "Childes", "Childing", "'Children' is the correct plural form of 'child'."],
    ["Who is the protagonist in 'Hamlet'?", "Hamlet", "Ophelia", "Macbeth", "Romeo", "The protagonist of 'Hamlet' is Prince Hamlet."],
    ["Which figure of speech gives human qualities to non-human objects?", "Personification", "Simile", "Metaphor", "Onomatopoeia", "Personification assigns human qualities to non-human things."],
    ["What is the subject of the sentence: 'The cat sat on the mat'?", "The cat", "The mat", "Sat", "On", "'The cat' is the subject of the sentence."],
    ["Which author wrote 'The Great Gatsby'?", "F. Scott Fitzgerald", "Ernest Hemingway", "Harper Lee", "J.K. Rowling", "F. Scott Fitzgerald wrote 'The Great Gatsby'."],
    ["What type of poem has 14 lines and a specific rhyme scheme?", "Sonnet", "Haiku", "Limerick", "Ballad", "A sonnet has 14 lines with a specific rhyme scheme."],
    ["What is an antonym for 'brave'?", "Cowardly", "Fearless", "Strong", "Daring", "An antonym for 'brave' is 'cowardly'."],
    ["Who wrote 'To Kill a Mockingbird'?", "Harper Lee", "J.D. Salinger", "George Orwell", "William Faulkner", "Harper Lee wrote 'To Kill a Mockingbird'."],
    ["What does 'hyperbole' mean?", "Extreme exaggeration", "Direct comparison", "Hinting at something", "Opposite meaning", "Hyperbole is an extreme exaggeration used for effect."],
    ["Which literary movement emphasized emotion and nature?", "Romanticism", "Realism", "Modernism", "Naturalism", "Romanticism emphasized emotion, nature, and individualism."],
    ["Who wrote '1984'?", "George Orwell", "Aldous Huxley", "Ray Bradbury", "Jules Verne", "George Orwell wrote '1984'."],
    ["Which type of noun refers to a person, place, or thing?", "Proper noun", "Abstract noun", "Collective noun", "Pronoun", "A proper noun refers to specific people, places, or things."],
    ["What is alliteration?", "Repetition of initial sounds", "Using a metaphor", "Making a comparison", "Telling a story", "Alliteration is the repetition of the same initial consonant sounds."],
    ["Which novel features the character Jay Gatsby?", "The Great Gatsby", "Moby *****", "Crime and Punishment", "Wuthering Heights", "Jay Gatsby is the main character in 'The Great Gatsby'."],
    ["What is the opposite of 'expand'?", "Shrink", "Grow", "Increase", "Enlarge", "The opposite of 'expand' is 'shrink'."],
    ["Which author wrote 'The Catcher in the Rye'?", "J.D. Salinger", "John Steinbeck", "Leo Tolstoy", "Virginia Woolf", "J.D. Salinger wrote 'The Catcher in the Rye'."],
    ["What does irony mean?", "Unexpected contrast between reality and expectations", "A direct statement", "A sound device", "A symbolic meaning", "Irony occurs when reality is different from expectations."],
    ["Who is the narrator in 'Moby-Dick'?", "Ishmael", "Ahab", "Starbuck", "Queequeg", "Ishmael is the narrator in 'Moby *****'."],
    ["What is the past tense of 'run'?", "Ran", "Runned", "Runs", "Running", "'Ran' is the correct past tense of 'run'."],
    ["Who wrote 'Frankenstein'?", "Mary Shelley", "Bram Stoker", "Edgar Allan Poe", "Charlotte Brontë", "Mary Shelley wrote 'Frankenstein'."],
    ["What is a simile?", "A comparison using 'like' or 'as'", "A direct statement", "An exaggeration", "A repeated sound", "A simile compares two things using 'like' or 'as'."],
    ["What literary device hints at future events?", "Foreshadowing", "Flashback", "Alliteration", "Hyperbole", "Foreshadowing provides hints about upcoming events in a story."],
    ["Who wrote 'Romeo and Juliet'?", "William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain", "William Shakespeare wrote 'Romeo and Juliet'."],
    ["What does a biography focus on?", "A person's life", "Fictional events", "Mythology", "Imaginary creatures", "A biography tells the life story of a real person."],
    ["What is the synonym for 'begin'?", "Start", "End", "Stop", "Pause", "A synonym for 'begin' is 'start'."],
    ["What is the setting of a story?", "Time and place", "Main character", "Conflict", "Theme", "The setting includes time and place where a story occurs."],
    ["Who wrote 'The Odyssey'?", "Homer", "Virgil", "Sophocles", "Plato", "Homer wrote 'The Odyssey'."],
    ["What is an allegory?", "A story with hidden meaning", "A direct statement", "A humorous exaggeration", "A type of rhyme", "An allegory is a story with a symbolic or hidden meaning."],
    ["Who wrote 'Macbeth'?", "William Shakespeare", "Christopher Marlowe", "John Milton", "Geoffrey Chaucer", "William Shakespeare wrote 'Macbeth'."],
    ["What is the main theme of 'Animal Farm'?", "Corruption of power", "Romantic love", "Exploration of space", "Coming of age", "'Animal Farm' explores the theme of power and corruption."],
    ["What is the difference between mood and tone?", "Mood is the reader's feeling, tone is the author's attitude", "Mood is the author’s attitude, tone is the reader's feeling", "They are the same", "Tone is only found in poetry", "Mood affects the reader, while tone reflects the author's attitude."],
    ["Who wrote 'Don Quixote'?", "Miguel de Cervantes", "Fyodor Dostoevsky", "Leo Tolstoy", "Herman Melville", "Miguel de Cervantes wrote 'Don Quixote'."],
    ["What is the correct comparative form of 'bad'?", "Worse", "Bader", "More bad", "Badder", "The comparative form of 'bad' is 'worse'."],
    ["What is the climax of a story?", "The most intense moment", "The introduction", "The conclusion", "The setting", "The climax is the most intense moment in a story."],
    ["Who wrote 'Les Misérables'?", "Victor Hugo", "Alexandre Dumas", "Gustave Flaubert", "Charles Dickens", "Victor Hugo wrote 'Les Misérables'."],
  ],
     Filipino: [
    ["Sino ang sumulat ng 'Noli Me Tangere'?", "Jose Rizal", "Andres Bonifacio", "Emilio Aguinaldo", "Francisco Balagtas", "Si Jose Rizal ang sumulat ng 'Noli Me Tangere'."],
    ["Ano ang kahulugan ng 'talinhaga'?", "Malalim na pahiwatig", "Tuwirang kahulugan", "Patula lamang", "Pang-uri ng salita", "Ang talinhaga ay isang malalim na pahiwatig o matalinghagang pananalita."],
    ["Ano ang tawag sa panitikang nagsasalaysay ng kasaysayan ng isang tao?", "Talambuhay", "Epiko", "Awit", "Bugtong", "Ang talambuhay ay kwento ng buhay ng isang tao."],
   
    ["Ano ang pangunahing tema ng 'Florante at Laura'?", "Pag-ibig at pagtataksil", "Digmaan", "Kalikasan", "Paglalakbay", "Ang pangunahing tema ng 'Florante at Laura' ay pag-ibig at pagtataksil."],
    ["Ano ang ibig sabihin ng tayutay?", "Matalinghagang pagpapahayag", "Tuwirang paliwanag", "Pag-uulit ng salita", "Paggamit ng pang-uri", "Ang tayutay ay matalinghagang pagpapahayag ng damdamin."],
    ["Ano ang kahulugan ng 'pabula'?", "Kwento tungkol sa hayop na may aral", "Kwento ng katatakutan", "Patulang panitikan", "Tula tungkol sa kalikasan", "Ang pabula ay isang kwentong may hayop bilang tauhan na may aral."],
    ["Ano ang salitang magkasalungat ng 'malungkot'?", "Masaya", "Mahina", "Matamlay", "Madilim", "Ang salitang magkasalungat ng 'malungkot' ay 'masaya'."],
    ["Sino ang may-akda ng 'Ibong Adarna'?", "Hindi tiyak", "Francisco Balagtas", "Jose Rizal", "Emilio Jacinto", "Ang may-akda ng 'Ibong Adarna' ay hindi tiyak dahil ito ay isang sinaunang akdang pampanitikan."],
    ["Ano ang palasak na anyo ng tula na may 4 na taludtod bawat saknong?", "Quatrain", "Couplet", "Soneto", "Balagtasan", "Ang quatrain ay isang uri ng tula na may apat na taludtod sa bawat saknong."],
    ["Ano ang tambalang salita ng 'bahaghari'?", "Bahag + Hari", "Bahagi + Hari", "Baha + Hari", "Bahay + Hari", "Ang tambalang salita ng 'bahaghari' ay 'bahag' at 'hari'."],
    ["Ano ang kahulugan ng idyoma na 'kapit sa patalim'?", "Pagsasakripisyo para sa pangangailangan", "Pag-aalaga ng matalim na bagay", "Pag-iiwas sa panganib", "Pagkawala ng pag-asa", "Ang 'kapit sa patalim' ay nangangahulugang pagsasakripisyo para sa pangangailangan."],
    ["Ano ang gamit ng pandiwa sa pangungusap: 'Siya ay tumakbo nang mabilis'?", "Kilos o galaw", "Ngalan ng tao", "Paglalarawan", "Pananda ng pang-abay", "Ang pandiwa ay tumutukoy sa kilos o galaw."],
    ["Ano ang kahulugan ng 'parabula'?", "Kwento na may aral mula sa bibliya", "Kwento ng hayop", "Kwento ng digmaan", "Kwento ng misteryo", "Ang parabula ay isang kwento na may aral mula sa bibliya."],
    ["Ano ang tawag sa paligsahan ng matatalas na debate sa pagtula?", "Balagtasan", "Bugtungan", "Talumpati", "Sanaysay", "Ang Balagtasan ay isang paligsahan ng pagtula na may matatalas na argumento."],
    ["Ano ang salitang ugat ng 'pinag-aralan'?", "Aral", "Pag-aaral", "Pinag-aral", "Nag-aral", "Ang salitang ugat ng 'pinag-aralan' ay 'aral'."],
    ["Ano ang kahulugan ng 'masining na pagpapahayag'?", "Malikhain at pino ang gamit ng salita", "Tuwirang paliwanag", "Pag-uulit ng impormasyon", "Makabago at teknikal na pagsasalita", "Ang masining na pagpapahayag ay malikhain at pino ang gamit ng salita."],
    ["Ano ang elemento ng tula na tumutukoy sa tunog at ritmo?", "Sukat at tugma", "Tema", "Tauhan", "Banghay", "Ang sukat at tugma ay elemento ng tula na tumutukoy sa tunog at ritmo."],
    ["Ano ang ibig sabihin ng 'Alamat'?", "Kwento ng pinagmulan ng isang bagay", "Kwento ng kasaysayan", "Kwento ng pantasya", "Kwento ng katatakutan", "Ang alamat ay kwento ng pinagmulan ng isang bagay o lugar."],
  ],
    Rizal: [
    ["Ano ang buong pangalan ni Dr. Jose Rizal?", "José Protacio Rizal Mercado y Alonso Realonda", "Jose Pedro Alonso Realonda Mercado Rizal", "Josito Alonso Realonda Mercado Rizal", "Jose Protacio Alonso Realonda Mercado Rizal", "Ang buong pangalan ni Jose Rizal ay José Protacio Rizal Mercado y Alonso Realonda."],
    ["Ano ang petsa ng kapanganakan ni Jose Rizal?", "Hunyo 19, 1861", "Hulyo 19, 1861", "Mayo 19, 1861", "Hunyo 18, 1961", "Si Jose Rizal ay ipinanganak noong Hunyo 19, 1861."],
    ["Ano ang unang nobela ni Rizal?", "Noli Me Tangere", "El Filibusterismo", "Mi Ultimo Adios", "La Solidaridad", "Ang unang nobela ni Rizal ay 'Noli Me Tangere'."],
    ["Ano ang pangunahing tema ng 'Noli Me Tangere'?", "Pang-aabuso ng mga Espanyol", "Pag-ibig", "Pakikibaka sa digmaan", "Paglalakbay", "Ang 'Noli Me Tangere' ay tumatalakay sa pang-aabuso ng mga Espanyol sa Pilipinas."],
    ["Ano ang ikalawang nobela ni Rizal?", "El Filibusterismo", "Noli Me Tangere", "La Solidaridad", "Mi Ultimo Adios", "Ang ikalawang nobela ni Rizal ay 'El Filibusterismo'."],
    ["Ano ang pangunahing tema ng 'El Filibusterismo'?", "Paghihiganti at rebolusyon", "Pag-ibig", "Paglalakbay", "Pang-aabuso ng mga Espanyol", "Ang 'El Filibusterismo' ay tumatalakay sa paghihiganti at rebolusyon."],
    ["Ano ang huling isinulat ni Rizal bago siya barilin?", "Mi Ultimo Adios", "El Filibusterismo", "Noli Me Tangere", "La Solidaridad", "Ang huling isinulat ni Rizal bago siya barilin ay 'Mi Ultimo Adios'."],
    ["Saan ipinanganak si Jose Rizal?", "Calamba, Laguna", "Manila", "Dapitan", "Intramuros", "Si Jose Rizal ay ipinanganak sa Calamba, Laguna."],
    ["Ano ang pangalan ng unang pag-ibig ni Rizal?", "Segunda Katigbak", "Leonor Rivera", "Josephine Bracken", "Suzanne Jacoby", "Ang unang pag-ibig ni Rizal ay si Segunda Katigbak."],
    ["Ano ang pangalan ng babaeng minahal ni Rizal na ipinagkasundo sa iba?", "Leonor Rivera", "Josephine Bracken", "Suzanne Jacoby", "Nellie Boustead", "Si Leonor Rivera ang babaeng minahal ni Rizal ngunit ipinagkasundo sa iba."],
    ["Ano ang pangalan ng babaeng naging asawa ni Rizal?", "Josephine Bracken", "Leonor Rivera", "Suzanne Jacoby", "Nellie Boustead", "Si Josephine Bracken ang naging asawa ni Rizal."],
    ["Ano ang pangunahing dahilan ng pagkakatapon ni Rizal sa Dapitan?", "Paghihinala ng mga Espanyol na siya ay nag-uudyok ng rebolusyon", "Paglalakbay sa ibang bansa", "Pag-aaral ng medisina", "Pagsulat ng tula", "Si Rizal ay ipinatapon sa Dapitan dahil sa paghihinala ng mga Espanyol na siya ay nag-uudyok ng rebolusyon."],
    ["Ano ang pangalan ng organisasyong itinatag ni Rizal?", "La Liga Filipina", "Katipunan", "La Solidaridad", "Propaganda Movement", "Ang La Liga Filipina ay isang organisasyong itinatag ni Rizal."],
    ["Ano ang layunin ng La Liga Filipina?", "Pagkakaisa ng mga Pilipino para sa reporma", "Pag-aalsa laban sa Espanya", "Pagpapalaganap ng Kristiyanismo", "Pag-aaral ng medisina", "Ang La Liga Filipina ay naglalayong pagkaisahin ang mga Pilipino para sa reporma."],
    ["Ano ang pangalan ng guro ni Rizal sa Ateneo?", "Padre Francisco de Paula Sanchez", "Padre Burgos", "Padre Damaso", "Padre Salvi", "Si Padre Francisco de Paula Sanchez ang guro ni Rizal sa Ateneo."],
    ["Ano ang kursong natapos ni Rizal sa UST?", "Medisina", "Abogasya", "Inhinyeriya", "Panitikan", "Si Rizal ay nagtapos ng medisina sa UST."],
    ["Ano ang pangalan ng kaibigan ni Rizal na isang Austrian?", "Dr. Ferdinand Blumentritt", "Dr. Reinhold Rost", "Dr. Jagor", "Dr. Karl Ulmer", "Si Dr. Ferdinand Blumentritt ay isang Austrian na naging kaibigan ni Rizal."],
    ["Ano ang pangalan ng barkong sinakyan ni Rizal papuntang Europa?", "Djemnah", "Hayfong", "Salvadora", "Belvic", "Ang barkong sinakyan ni Rizal papuntang Europa ay Djemnah."],
    ["Ano ang eksaktong oras ng pagkamatay ni Rizal?", "7:03 AM", "6:00 AM", "6:30 AM", "8:00 AM", "Si Rizal ay binaril at namatay noong 7:03 AM."],
    ["Ano ang pangalan ng bantayog kung saan binaril si Rizal?", "Bagumbayan", "Intramuros", "Fort Santiago", "Dapitan", "Si Rizal ay binaril sa Bagumbayan, na ngayon ay tinatawag na Luneta."],
    ["Ano ang pangalan ng kapatid ni Rizal na tumulong sa kanyang mga sulatin?", "Paciano Rizal", "Soledad Rizal", "Narcisa Rizal", "Trinidad Rizal", "Si Paciano Rizal ang kapatid ni Jose Rizal na tumulong sa kanyang mga sulatin."],
    ["Ano ang pangalan ng artikulo ni Rizal na nagpapahayag ng pagmamahal sa bayan?", "Amor Patrio", "La Solidaridad", "Mi Ultimo Adios", "Los Viajes", "Ang 'Amor Patrio' ay isang artikulo ni Rizal na nagpapahayag ng pagmamahal sa bayan."],
    ["Ano ang tawag sa kilusan na naglalayong ipaglaban ang reporma sa Pilipinas?", "Propaganda Movement", "Katipunan", "La Liga Filipina", "Revolusyon", "Ang Propaganda Movement ay isang kilusan na naglalayong ipaglaban ang reporma sa Pilipinas."],
    ["Ano ang pangunahing dahilan ng pagkamatay ni Rizal?", "Pinarusahan ng mga Espanyol dahil sa kanyang mga akda", "Sakit", "Paglalakbay sa ibang bansa", "Pag-aaral ng medisina", "Si Rizal ay pinatay ng mga Espanyol dahil sa kanyang mga akda at adbokasiya."],
  ],
  };

