const rizalQuestions = [
    ["Ano ang buong pangalan ni Dr. Jose Rizal?", "José Protacio Rizal Mercado y Alonso Realonda", "Jose Pedro Alonso Realonda Mercado Rizal", "Josito Alonso Realonda Mercado Rizal", "Jose Protacio Alonso Realonda Mercado Rizal", "Ang buong pangalan ni Jose Rizal ay José Protacio Rizal Mercado y Alonso Realonda."],
    ["Ano ang petsa ng kapanganakan ni Jose Rizal?", "Hunyo 19, 1861", "Hulyo 19, 1861", "Mayo 19, 1861", "Hunyo 18, 1961", "Si Jose Rizal ay ipinanganak noong Hunyo 19, 1861."],
    ["Ano ang unang nobela ni Rizal?", "Noli Me Tangere", "El Filibusterismo", "Mi Ultimo Adios", "La Solidaridad", "Ang unang nobela ni Rizal ay 'Noli Me Tangere'."],
    ["Ano ang pangunahing tema ng 'Noli Me Tangere'?", "Pang-aabuso ng mga Espanyol", "Pag-ibig", "Pakikibaka sa digmaan", "Paglalakbay", "Ang 'Noli Me Tangere' ay tumatalakay sa pang-aabuso ng mga Espanyol sa Pilipinas."],
    ["Ano ang ikalawang nobela ni Rizal?", "El Filibusterismo", "Noli Me Tangere", "La Solidaridad", "Mi Ultimo Adios", "Ang ikalawang nobela ni Rizal ay 'El Filibusterismo'."],
    ["Ano ang pangunahing tema ng 'El Filibusterismo'?", "Paghihiganti at rebolusyon", "Pag-ibig", "Paglalakbay", "Pang-aabuso ng mga Espanyol", "Ang 'El Filibusterismo' ay tumatalakay sa paghihiganti at rebolusyon."],
    ["Ano ang huling isinulat ni Rizal bago siya barilin?", "Mi Ultimo Adios", "El Filibusterismo", "Noli Me Tangere", "La Solidaridad", "Ang huling isinulat ni Rizal bago siya barilin ay 'Mi Ultimo Adios'."],
    ["Saan ipinanganak si Jose Rizal?", "Calamba, Laguna", "Manila", "Dapitan", "Intramuros", "Si Jose Rizal ay ipinanganak sa Calamba, Laguna."],
    ["Ano ang pangalan ng unang pag-ibig ni Rizal?", "Segunda Katigbak", "Leonor Rivera", "Josephine Bracken", "Suzanne Jacoby", "Ang unang pag-ibig ni Rizal ay si Segunda Katigbak."],
    ["Ano ang pangalan ng babaeng minahal ni Rizal na ipinagkasundo sa iba?", "Leonor Rivera", "Josephine Bracken", "Suzanne Jacoby", "Nellie Boustead", "Si Leonor Rivera ang babaeng minahal ni Rizal ngunit ipinagkasundo sa iba."],
    ["Ano ang pangalan ng babaeng naging asawa ni Rizal?", "Josephine Bracken", "Leonor Rivera", "Suzanne Jacoby", "Nellie Boustead", "Si Josephine Bracken ang naging asawa ni Rizal."],
    ["Ano ang pangunahing dahilan ng pagkakatapon ni Rizal sa Dapitan?", "Paghihinala ng mga Espanyol na siya ay nag-uudyok ng rebolusyon", "Paglalakbay sa ibang bansa", "Pag-aaral ng medisina", "Pagsulat ng tula", "Si Rizal ay ipinatapon sa Dapitan dahil sa paghihinala ng mga Espanyol na siya ay nag-uudyok ng rebolusyon."],
    ["Ano ang pangalan ng organisasyong itinatag ni Rizal?", "La Liga Filipina", "Katipunan", "La Solidaridad", "Propaganda Movement", "Ang La Liga Filipina ay isang organisasyong itinatag ni Rizal."],
    ["Ano ang layunin ng La Liga Filipina?", "Pagkakaisa ng mga Pilipino para sa reporma", "Pag-aalsa laban sa Espanya", "Pagpapalaganap ng Kristiyanismo", "Pag-aaral ng medisina", "Ang La Liga Filipina ay naglalayong pagkaisahin ang mga Pilipino para sa reporma."],
    ["Ano ang pangalan ng guro ni Rizal sa Ateneo?", "Padre Francisco de Paula Sanchez", "Padre Burgos", "Padre Damaso", "Padre Salvi", "Si Padre Francisco de Paula Sanchez ang guro ni Rizal sa Ateneo."],
    ["Ano ang kursong natapos ni Rizal sa UST?", "Medisina", "Abogasya", "Inhinyeriya", "Panitikan", "Si Rizal ay nagtapos ng medisina sa UST."],
    ["Ano ang pangalan ng kaibigan ni Rizal na isang Austrian?", "Dr. Ferdinand Blumentritt", "Dr. Reinhold Rost", "Dr. Jagor", "Dr. Karl Ulmer", "Si Dr. Ferdinand Blumentritt ay isang Austrian na naging kaibigan ni Rizal."],
    ["Ano ang pangalan ng barkong sinakyan ni Rizal papuntang Europa?", "Djemnah", "Hayfong", "Salvadora", "Belvic", "Ang barkong sinakyan ni Rizal papuntang Europa ay Djemnah."],
    ["Ano ang eksaktong oras ng pagkamatay ni Rizal?", "7:03 AM", "6:00 AM", "6:30 AM", "8:00 AM", "Si Rizal ay binaril at namatay noong 7:03 AM."],
    ["Ano ang pangalan ng bantayog kung saan binaril si Rizal?", "Bagumbayan", "Intramuros", "Fort Santiago", "Dapitan", "Si Rizal ay binaril sa Bagumbayan, na ngayon ay tinatawag na Luneta."],
    ["Ano ang pangalan ng kapatid ni Rizal na tumulong sa kanyang mga sulatin?", "Paciano Rizal", "Soledad Rizal", "Narcisa Rizal", "Trinidad Rizal", "Si Paciano Rizal ang kapatid ni Jose Rizal na tumulong sa kanyang mga sulatin."],
    ["Ano ang pangalan ng artikulo ni Rizal na nagpapahayag ng pagmamahal sa bayan?", "Amor Patrio", "La Solidaridad", "Mi Ultimo Adios", "Los Viajes", "Ang 'Amor Patrio' ay isang artikulo ni Rizal na nagpapahayag ng pagmamahal sa bayan."],
    ["Ano ang tawag sa kilusan na naglalayong ipaglaban ang reporma sa Pilipinas?", "Propaganda Movement", "Katipunan", "La Liga Filipina", "Revolusyon", "Ang Propaganda Movement ay isang kilusan na naglalayong ipaglaban ang reporma sa Pilipinas."],
    ["Ano ang pangunahing dahilan ng pagkamatay ni Rizal?", "Pinarusahan ng mga Espanyol dahil sa kanyang mga akda", "Sakit", "Paglalakbay sa ibang bansa", "Pag-aaral ng medisina", "Si Rizal ay pinatay ng mga Espanyol dahil sa kanyang mga akda at adbokasiya."],
  ];
